src/EPIDIWeb/Controllers/BDMController.cs
using Epidi.Models.Paging;
using Epidi.Models.ViewModel.BDM;
using Epidi.Models.ViewModel.BDMCommisionMarkUpSettingInstrumentWise;
using Epidi.Models.ViewModel.Common;
using Epidi.Models.ViewModel.IBCommissionMarkUpSettingInstrumentWise;
using Epidi.Models.ViewModel.TradeRule;
using Epidi.Service.BDM;
using Epidi.Service.IBCommisionMarkUpSettingInstrumentWise;
using EPIDIWeb.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.HSSF.Util;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.Data;

namespace EPIDIWeb.Controllers
{
    public class BDMController : Controller
    {
        private readonly IBDMService _BDMService;
        private readonly IIBCommisionMarkUpSettingInstWiseService _iCommissionSetting;
        //private readonly IIn

         public BDMController(IBDMService bDMService, IIBCommisionMarkUpSettingInstWiseService iCommissionSetting)
        {
            _BDMService = bDMService;
            _iCommissionSetting = iCommissionSetting;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "BDM List";
            return View();
        }
        public IActionResult AddBDM()
        {
            GetInstruments();
            return View(new BDMViewModel());
        }
        [HttpPost]
        public JsonResult Get_All()
        {
            {
                long totalRecord = 0;
                long filteredRecord = 0;
                var Draw = Request.Form["draw"].FirstOrDefault();
                PageParam pageParam = new PageParam();

                pageParam.Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");


                pageParam.Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
                string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
                var response = _iCommissionSetting.GetAll_Commission(pageParam, search);

                totalRecord = response.Item2;
                filteredRecord = response.Item2;

                return Json(new { draw = Draw, recordsTotal = totalRecord, recordsFiltered = filteredRecord, data = response.Item1 });
            }
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> SaveBDM(BDMViewModel model)
        {
            try
            {
                ResponseViewModel responseViewModel = new ResponseViewModel();
                if (model != null)
                {
                    var res = await _BDMService.Upsert(model);
                    if (res != null)
                    {
                        responseViewModel.Code = 200;
                        responseViewModel.Message = "BDM Saved Successfully";
                    }
                    else
                    {
                        responseViewModel.Code = 400;
                        responseViewModel.Message = "BDM Not Saved";
                    }
                    return Json(responseViewModel);
                }
                else
                {
                    return Json("");
                }
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }
        public void GetInstruments()
        {
            var FieldsList = _BDMService.Get_All_Instrument().Result.Select(p => new SelectListItem()
            {
                Value = p.Id.ToString(),
                Text = p.Name
            });

            ViewBag.InstrumentList = FieldsList;
        }



        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var response = await _BDMService.GetById(Id);
            //response.FieldName =    
            GetInstruments();
            if (response != null)
            {
                return View("AddBDM", response);
            }
            else
            {
                return View(new BDMViewModel());
            }
        }
        public async Task<IActionResult> IBCommision(int IBID, string IBName = "")
        {
            //GetInstruments();
            var model = new CommisionMarkUpSetting();
            model.IbId = IBID;
            model.IbName = IBName;
            //if (IBID > 0)
            //{
            //    model.IbId = IBID;
            //    var response = _iCommissionSetting.GetIBMCommision_IBID(IBID);
            //    if (response != null)
            //    {
            //        return View("IBCommision", response);
            //    }
            //    else
            //    {
            //        if (IBName != "")
            //        {
            //            model.IbName = IBName;
            //        }
            //        goto CallBlankModel;
            //    }
            //}
            //else
            //{
            //    goto CallBlankModel;
            //}
            //////goto statement is jump statement
            //CallBlankModel:
            return View("IBCommision", model);
        }


        [HttpPost]
        public async Task<IActionResult> SaveBDMCommision(BDMCommisionMarkUpSettingInstrumentWiseViewModel model)
        {
            try
            {
                ResponseViewModel responseViewModel = new ResponseViewModel();
                if (model != null)
                {
                    var res = await _BDMService.SaveBDMCommision(model);
                    if (res != null)
                    {
                        responseViewModel.Code = 200;
                        responseViewModel.Message = "BDM Saved Successfully";
                    }
                    else
                    {
                        responseViewModel.Code = 400;
                        responseViewModel.Message = "BDM Not Saved";
                    }
                    return Json(responseViewModel);
                }
                else
                {
                    return Json("");
                }
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }
        [HttpPost]
        public async Task<IActionResult> SaveIBInstrumentCommission(CommisionMarkUpSetting model)
        {
            try
            {
                List<CommisionMarkUpSetting> commisionMarkUpSetting = new List<CommisionMarkUpSetting>();
                commisionMarkUpSetting = JsonConvert.DeserializeObject<List<CommisionMarkUpSetting>>(model.objCommissionString);

                ListToDataTableConverter converter = new ListToDataTableConverter();

                DataTable dtRuleInstrument = converter.ToDataTable(commisionMarkUpSetting);
                dtRuleInstrument.Columns.Remove("BdmName");
                dtRuleInstrument.Columns.Remove("IbNo");
                dtRuleInstrument.Columns.Remove("IbName");
                dtRuleInstrument.Columns.Remove("objCommissionString");

                _iCommissionSetting.CommisionMarkUpSetting_UpsertByDt(dtRuleInstrument);
                return Json(new { StatusCode = 200, Message = "IB Commission updated Successfully" });
            }
            catch (Exception ex)
            {
                return Json(new { StatusCode = 400, Message = ex.Message.ToString() });
            }
        }
        [HttpGet]
        public async Task<JsonResult> Get_CommissionInstrumentWise(int Ib_Id, int instrument_filter)
        {
            var response = await _iCommissionSetting.GetIBMCommision_IBID(Ib_Id, instrument_filter);
            return Json(response);
        }

        [HttpPost]
        public async Task<IActionResult> UploadBDMInstrument(IFormFile FileUpload, CommisionMarkUpSetting reqModel)
        {
            string filePath = string.Empty;
            try
            {
                if (FileUpload != null)
                {
                    IWorkbook workbook;
                    var supportedTypes = new[] { "xls", "xlsx" };
                    var fileExt = Path.GetExtension(FileUpload.FileName);
                    fileExt = fileExt.Replace(".", "");
                    if (!supportedTypes.Contains(fileExt))
                    {
                        return Json(new { StatusCode = 400, Message = "Please Select valid file." });
                    }
                    else
                    {
                        if (fileExt.Equals("xls"))
                        {
                            //FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
                            workbook = new HSSFWorkbook(FileUpload.OpenReadStream(), true);
                        }
                        else
                        {
                            workbook = new XSSFWorkbook(FileUpload.OpenReadStream());
                        }

                        ISheet sheet = workbook.GetSheetAt(0);

                        try
                        {
                            IRow HeaderRow = sheet.GetRow(0);
                            List<CommisionMarkUpSetting> _commisionMarkUpSetting = new List<CommisionMarkUpSetting>();

                            int id = 0;
                            int MasterInstrumentalId = 0;
                            double MarkUpPer1000 = 0;
                            int IBID = reqModel.IbId;
                            double MarkUpPer = 0;
                            double BuySwapPer1000 = 0;
                            double BuySwapPer = 0;
                            double SellSwapPer1000 = 0;
                            double SellSwapPer = 0;
                            double BDMID = 0; 

                            var FieldsList = _BDMService.Get_All_Instrument().Result.Select(p => new SelectListItem() { Value = p.Id.ToString(), Text = p.Name });

                            for (int rowNo = 1; rowNo < sheet.PhysicalNumberOfRows; rowNo++)
                            {

src/EPIDIWeb/Views/BDM/AddBDM.cshtml
@model BDMViewModel
@{
    Layout = null;
}
@using (Html.BeginForm("SaveBDM", "BDM", FormMethod.Post, new { id = "bdmForm" }))
{
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                @Html.HiddenFor(model => model.Id)
                @Html.LabelFor(model => model.Name, "Name")
                @Html.TextBoxFor(p => p.Name, new { @class = "form-control", @placeholder = "Name" ,@name="Name"})
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BDMCommision.MarkUpPer1000, "MarkUpPer1000")
                @Html.TextBoxFor(p => p.BDMCommision.MarkUpPer1000, new { @class = "form-control", @placeholder = "MarkUpPer1000" ,@name="MarkUpPer1000",type = "number",step="any"})
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BDMCommision.MarkUpPer, "Mark Up Per%")
                @Html.TextBoxFor(p => p.BDMCommision.MarkUpPer, new { @class = "form-control", @placeholder = "MarkUpPer" ,@name="MarkUpPer",type = "number"})
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BDMCommision.BuySwapPer1000, "BuySwapPer1000")
                @Html.TextBoxFor(p => p.BDMCommision.BuySwapPer1000, new { @class = "form-control", @placeholder = "BuySwapPer1000" ,@name="BuySwapPer1000",type = "number"})
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BDMCommision.BuySwapPer, "Buy Swap Per%")
                @Html.TextBoxFor(p => p.BDMCommision.BuySwapPer, new { @class = "form-control", @placeholder = "Buy Swap Per%" ,@name="BuySwapPer",type = "number"})
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BDMCommision.SellSwapPer1000, "SellSwapPer1000")
                @Html.TextBoxFor(p => p.BDMCommision.SellSwapPer1000, new { @class = "form-control", @placeholder = "SellSwapPer1000" ,@name="SellSwapPer1000",type = "number"})
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                @Html.LabelFor(model => model.BDMCommision.SellSwapPer, "Sell Swap Per%")
                @Html.TextBoxFor(p => p.BDMCommision.SellSwapPer, new { @class = "form-control", @placeholder = "Sell Swap Per%" ,@name="SellSwapPer",type = "number"})
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
}