src/EPIDIWeb/Controllers/ImportInstrumentsController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Office2010.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Epidi.Models.Paging;
using Epidi.Models.ViewModel.Common;
using Epidi.Models.ViewModel.Instrument;
using Epidi.Models.ViewModel.LeverageRules;
using Epidi.Models.ViewModel.RuleCondition;
using Epidi.Models.ViewModel.SwapRule;
using Epidi.Service.BDM;
using Epidi.Service.InstrumentService;
using Epidi.Service.RuleConditionService;
using EPIDIWeb.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.Util;
using NPOI.XSSF.UserModel;
using SendGrid;
using System.Data;
using System.Text;

namespace EPIDIWeb.Controllers
{
    public class ImportInstrumentsController : Controller
    {
        private readonly IInstrumentService _instrumentService;
        private readonly IRuleConditionService _ruleConditionService;
        private readonly IBDMService _BDMService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ImportInstrumentsController(IInstrumentService instrumentService, IWebHostEnvironment webHostEnvironment,
            IRuleConditionService ruleConditionService,
            IBDMService BDMService)
        {
            _instrumentService = instrumentService;
            _ruleConditionService = ruleConditionService;
            _BDMService = BDMService;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            ViewBag.Title = "Instrument Specification List ";
            return View();
        }

        public IActionResult ImportGateIO()
        {
            return View();
        }
        public IActionResult ImportLMAX()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, int tradeId)
        {
            PageParam pageParam = new PageParam();
            pageParam.Offset = 0;
            pageParam.Limit = 1000000;
            var instruments = await _instrumentService.GetAllInstrument(pageParam, "");
            var symbolgroup = await _instrumentService.GetAllSymbolGroup();
            var tradeStatus = await _instrumentService.GetAllTradeStatus();
            ViewBag.Instruments = instruments.Item1;
            ViewBag.Symbolgroup = symbolgroup;
            ViewBag.TradeStatus = tradeStatus;
            var model = await _instrumentService.GetByID(id, tradeId);
            return PartialView("Edit", model);
        }
        public async Task<IActionResult> UpdateSpecifications(MasterInstrumentViewModel model)
        {
            var res = await _instrumentService.UpdateInstrumentMaster(model);
            return Json(res);

        }
        public async Task<IActionResult> EditSpecificationRule(int id)
        {
            //PageParam pageParam = new PageParam();
            //pageParam.Offset = 0;
            //pageParam.Limit = 1000000;
            //var instruments = await _instrumentService.GetAllInstrument(pageParam, "");
            //var symbolgroup = await _instrumentService.GetAllSymbolGroup();
            //var tradeStatus = await _instrumentService.GetAllTradeStatus();
            //ViewBag.Instruments = instruments.Item1;
            //ViewBag.Symbolgroup = symbolgroup;
            //ViewBag.TradeStatus = tradeStatus;

            var response = await _instrumentService.GetSpecificationRuleByID(id);

            var ruleConditions = await _ruleConditionService.GetRuleConditionBySpecificationRuleId(id);
            response.objRuleConditionViewModel = ruleConditions;
            if (ruleConditions != null)
            {
                response.objRuleConditionViewModel.conditionRulesDtlObj = JsonConvert.SerializeObject(ruleConditions.rulesDtlViewModel);
            }

            return PartialView("EditSpecificationRule", response);
        }


        [HttpPost]
        public async Task<JsonResult> All_Import_MasterInstrument(int Id)
        {
            long totalRecord;
            long filteredRecord;
            var Draw = Request.Form["draw"].FirstOrDefault();
            PageParam pageParam = new()
            {
                Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0"),
                Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0")
            };

            string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
            var response = await _instrumentService.GetAllImportMasterInstrument(Id, pageParam,search).ConfigureAwait(false);

            totalRecord = response.Item2;
            filteredRecord = response.Item2;

            return Json(new { draw = Draw, recordsTotal = totalRecord, recordsFiltered = filteredRecord, data = response.Item1 });
        }
        [HttpPost]
        public async Task<JsonResult> All_SpecificationRule()
        {
            long totalRecord;
            long filteredRecord;
            var Draw = Request.Form["draw"].FirstOrDefault();
            PageParam pageParam = new()
            {
                Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0"),
                Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0")
            };

            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();


            string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
            var response = await _instrumentService.GetAllSpecificationRule(pageParam, search).ConfigureAwait(false);

            totalRecord = response.Item2;
            filteredRecord = response.Item2;

            var responseData = OrderByExtension.OrderBy(response.Item1.AsQueryable(), sortColumn, sortColumnDirection).ToList();


            return Json(new { draw = Draw, recordsTotal = totalRecord, recordsFiltered = filteredRecord, data = responseData });
        }

        [HttpPost]
        public async Task<JsonResult> All_Import_GATEIO()
        {
            long totalRecord;
            long filteredRecord;
            var Draw = Request.Form["draw"].FirstOrDefault();
            PageParam pageParam = new()
            {
                Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0"),
                Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0")
            };

            string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
            var response = await _instrumentService.GetAllImportGATEIO(pageParam, search).ConfigureAwait(false);

            totalRecord = response.Item2;
            filteredRecord = response.Item2;

            return Json(new { draw = Draw, recordsTotal = totalRecord, recordsFiltered = filteredRecord, data = response.Item1 });
        }

        [HttpPost]
        public async Task<JsonResult> All_Import_LMAX()
        {
            long totalRecord;
            long filteredRecord;
            var Draw = Request.Form["draw"].FirstOrDefault();
            PageParam pageParam = new()
            {
                Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0"),
                Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0")
            };

            string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
            var response = await _instrumentService.GetAllImportLMax(pageParam, search).ConfigureAwait(false);

            totalRecord = response.Item2;
            filteredRecord = response.Item2;

            return Json(new { draw = Draw, recordsTotal = totalRecord, recordsFiltered = filteredRecord, data = response.Item1 });
        }

        [HttpPost]
        public async Task<IActionResult> UploadGateIOInstrumentsExcel(IFormFile FileUpload)
        {
            string filePath = string.Empty;
            try
            {
                if (FileUpload != null)
                {
                    IWorkbook workbook;
                    var supportedTypes = new[] { "xls", "xlsx" };
                    var fileExt = Path.GetExtension(FileUpload.FileName);
                    fileExt = fileExt.Replace(".", "");
                    if (!supportedTypes.Contains(fileExt))
                    {
                        return Json(new { StatusCode = 400, Message = "Please Select valid file." });
                    }
                    else
                    {
                        if (fileExt.Equals("-xls"))
                        {
                            //FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
                            workbook = new HSSFWorkbook(FileUpload.OpenReadStream(), true);
                        }
                        else
                        {
                            workbook = new XSSFWorkbook(FileUpload.OpenReadStream());
                        }

                        ISheet sheet = workbook.GetSheetAt(0);

                        try
                        {
                            IRow HeaderRow = sheet.GetRow(0);

                            List<GateIOInstrumentMappingViewModel> gateIOInstrumentMappingViewModels = new List<GateIOInstrumentMappingViewModel>();

                            string Name;
                            int tradeStatus;
                            string Base;
                            string quote;
                            decimal fee;
                            decimal minBaseAmount;
                            decimal minQuoteAmount;
                            decimal amountPrecision;
                            decimal precision;
                            decimal sellStart;
                            decimal buyStart;

src/EPIDIWeb/Views/ImportInstruments/ImportGateIO.cshtml
@{
    ViewBag.PageTitle = "Import Instrument";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    ViewBag.Method = "Instrument Mapping";
}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-6">
                        @using (Html.BeginForm("UploadGateIOInstrumentsExcel", "ImportInstruments", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmGATEIOExcelForm" }))//onsubmit = "return myFunction()"
                        {
                            <div class="custom-file form-group float-sm-left mr-3" style="width:230px">
                                <input type="file" id="FileUpload" name="FileUpload" class="custom-file-input">
                                <label id="GatelblName" class="custom-file-label" style="text-align:left" for="file">Choose GATEIO Instrument</label>
                            </div>
                            <button type="submit" class="btn btn-info form-group float-sm-left mr-3 ">Import GATEIO Instruments</button>
                        }
                    </div>
                </div>

            </div>
            <div class="card-body">
                <table id="gateIO" class="table table-bordered table-striped">
                </table>
            </div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
@section Scripts
    {
    <script src="~/js/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/js/jquery-validation/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    
    <script>
        $(document).ready(() => {

            GATEIOInstrumentDataTable.init();

            $('#FileUpload').on('change', function (e) {
                //get the file name
                var fileName = e.target.files[0].name;
                $(this).next('.custom-file-label').html(fileName);
            })

            $(document).on("submit", "#frmGATEIOExcelForm", function (e) {
                e.preventDefault();
                debugger
                var form = $(this);
                form.ajaxSubmit({
                    beforeSubmit: function () {
                        if (!form.valid()) {

                            return false;
                        }
                        else {

                            return true;
                        }
                    },
                    success: function (res) {
                        debugger
                        if (res.statusCode == 200) {
                            $('#FileUpload').val('');
                            $('#GatelblName').html('Choose GATEIO Instrument')
                            NotifyMsg('success', res.message);

                        } else {
                            NotifyMsg('error', res.message);
                        }
                    },
                    Errors: function () {

                        NotifyMsg('error', res.message);
                    }
                });
                return false;
            });

        });

        var GATEIOInstrumentDataTable = function () {
            let initTable1 = function () {
                let table = $('#gateIO');

                let oTable = table.dataTable({
                    "stateSave": true,
                    "autoWidth": false,
                    "paging": true,
                    // Internationalisation. For more info refer to http://datatables.net/manual/i18n
                    "language": {
                        "aria": {
                            "sortAscending": ": activate to sort column ascending",
                            "sortDescending": ": activate to sort column descending"
                        },
                        "emptyTable": "No data available in table",
                        "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                        "infoEmpty": "No entries found",
                        "infoFiltered": "(filtered1 from MAX total entries)",
                        //"lengthMenu": "MENU entries",
                        "search": "Search:",
                        "zeroRecords": "No matching records found"
                    },
                    "pageLength": 10,
                    "processing": true,
                    "serverSide": true,
                    "ajax": {
                        async: false,
                        url: '/ImportInstruments/All_Import_GATEIO',
                        type: "post",
                    },
                    "columns": [

                        {
                            "title": "Name", "data": "name", "orderable": false, "width": "3%"
                        },
                        {
                            "title": "Base", "data": "base", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "Quote", "data": "quote", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "Fee", "data": "fee", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "MinBaseAmount", "data": "minBaseAmount", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "MinQuoteAmount", "data": "minQuoteAmount", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "AmountPrecision", "data": "amountPrecision", "orderable": false, "width": "1%"
                        },
                         {
                            "title": "Precision", "data": "precision", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "SellStart", "data": "sellStart", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "BuyStart", "data": "buyStart", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "Action", "data": "id",
                            "render": function (data, type, row) {
                                let htmlData = "";

                                htmlData += '<input type="hidden" value=' + row['id'] + ' />'
                                htmlData += `<button title="Edit TradeTiming" class="btn btn-sm btn-success mr-1" onclick="GetTradeTimingById($(this));"><i class="fa fa-edit"></i></button>`;
                                htmlData += `<button title="Delete TradeTiming" class="btn btn-sm btn-danger mr-1" onclick="DeleteTradeTiming($(this));"><i class="fa fa-trash"></i></button>`;
                                return htmlData;
                            }
                            , "orderable": false, "width": "3%"
                        },
                    ],

                    // setup responsive extension: http://datatables.net/extensions/responsive/
                    responsive: true,

                    "lengthMenu": [
                        [5, 10, 15, 20, 1000],
                        [5, 10, 15, 20, 1000] // change per page values here
                    ],
                    // set the initial value

                    //"dom": "<'row' <'col-md-12'B>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

                    // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                    // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
                    // So when dropdowns used the scrollable div should be removed.
                    //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",
                });
            }

            return {
                init: function () {
                    if ($.fn.DataTable.isDataTable("#TradeTimingList")) {
                        $('#TradeTimingList').dataTable().fnDestroy();
                        //$('#divUserTable').html('<table class="table table-striped" width="100%" id="UserTable"></table>');
                    }
                    initTable1();
                }
            };
        }();

    </script>
}

src/EPIDIWeb/Views/ImportInstruments/ImportLMAX.cshtml
@{
    ViewBag.PageTitle = "Import Instrument";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    ViewBag.Method = "Instrument Mapping";
}


<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-6">
                        @using (Html.BeginForm("UploadLMaxInstrumentsExcel", "ImportInstruments", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmLMAXExcelForm" }))//onsubmit = "return myFunction()"
                        {
                            <div class="custom-file form-group float-sm-left mr-3" style="width:230px">
                                <input type="file" id="LMAXUpload" name="LMAXUpload" class="custom-file-input">
                                <label id="LmaxlblName" class="custom-file-label" style="text-align:left" for="file">Choose LMAX Instruments</label>
                            </div>
                            <button type="submit" class="btn btn-info form-group float-sm-left mr-3 ">Import LMAX Instruments</button>
                        }
                    </div>
                </div>

            </div>
            <div class="card-body">
                <table id="lMAX" class="table table-bordered table-striped">
                </table>
            </div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
@section Scripts
    {
    <script src="~/js/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/js/jquery-validation/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script>
        $(document).ready(() => {

            LMAXInstrumentDataTable.init();

            $('#LMAXUpload').on('change', function (e) {
                //get the file name
                debugger
                var fileName = e.target.files[0].name;
                $(this).next('.custom-file-label').html(fileName);
            })



            $(document).on("submit", "#frmLMAXExcelForm", function (e) {
                e.preventDefault();
                debugger
                var form = $(this);
                form.ajaxSubmit({
                    beforeSubmit: function () {
                        if (!form.valid()) {

                            return false;
                        }
                        else {

                            return true;
                        }
                    },
                    success: function (res) {
                        debugger
                        if (res.statusCode == 200) {
                            $('#LMAXUpload').val('');
                            $('#LmaxlblName').html('Choose LMAX Instruments')
                            NotifyMsg('success', res.message);

                        } else {
                            NotifyMsg('error', res.message);
                        }
                    },
                    Errors: function () {

                        NotifyMsg('error', res.message);
                    }
                });
                return false;
            });

        });

        var LMAXInstrumentDataTable = function () {
            let initTable1 = function () {
                let table = $('#lMAX');

                let oTable = table.dataTable({
                    "stateSave": true,
                    "autoWidth": false,
                    "paging": true,
                    // Internationalisation. For more info refer to http://datatables.net/manual/i18n
                    "language": {
                        "aria": {
                            "sortAscending": ": activate to sort column ascending",
                            "sortDescending": ": activate to sort column descending"
                        },
                        "emptyTable": "No data available in table",
                        "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                        "infoEmpty": "No entries found",
                        "infoFiltered": "(filtered1 from MAX total entries)",
                        //"lengthMenu": "MENU entries",
                        "search": "Search:",
                        "zeroRecords": "No matching records found"
                    },
                    "pageLength": 10,
                    "processing": true,
                    "serverSide": true,
                    "ajax": {
                        async: false,
                        url: '/ImportInstruments/All_Import_LMAX',
                        type: "post",
                    },
                    "columns": [

                        {
                            "title": "Symbol", "data": "symbol", "orderable": false, "width": "3%"
                        },
                        {
                            "title": "Currency", "data": "currency", "orderable": false, "width": "3%"
                        },
                        {
                            "title": "UOM", "data": "uom", "orderable": false, "width": "3%"
                        },
                        {
                            "title": "AssetClass", "data": "assetClass", "orderable": false, "width": "3%"
                        },
                        {
                            "title": "QtyIncrement", "data": "qtyIncrement", "orderable": false, "width": "3%"
                        },
                        {
                            "title": "PriceIncrement", "data": "priceIncrement", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "TickerEnabled", "data": "tickerEnabled", "orderable": false, "width": "1%"
                        },
                        {
                            "title": "Action", "data": "id",
                            "render": function (data, type, row) {
                                let htmlData = "";

                                htmlData += '<input type="hidden" value=' + row['id'] + ' />'
                                htmlData += `<button title="Edit TradeTiming" class="btn btn-sm btn-success mr-1" onclick="GetTradeTimingById($(this));"><i class="fa fa-edit"></i></button>`;
                                htmlData += `<button title="Delete TradeTiming" class="btn btn-sm btn-danger mr-1" onclick="DeleteTradeTiming($(this));"><i class="fa fa-trash"></i></button>`;
                                return htmlData;
                            }
                            , "orderable": false, "width": "3%"
                        },
                    ],

                    // setup responsive extension: http://datatables.net/extensions/responsive/
                    responsive: true,

                    "lengthMenu": [
                        [5, 10, 15, 20, 1000],
                        [5, 10, 15, 20, 1000] // change per page values here
                    ],
                    // set the initial value

                    //"dom": "<'row' <'col-md-12'B>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

                    // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
                    // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
                    // So when dropdowns used the scrollable div should be removed.
                    //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",
                });
            }

            return {
                init: function () {
                    if ($.fn.DataTable.isDataTable("#TradeTimingList")) {
                        $('#TradeTimingList').dataTable().fnDestroy();
                        //$('#divUserTable').html('<table class="table table-striped" width="100%" id="UserTable"></table>');
                    }
                    initTable1();
                }
            };
        }();

    </script>
}

src/EPIDIWeb/Views/ImportInstruments/ImportSpecificationRule.cshtml
@model InstrumentSpecificationRule
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    ViewBag.PageTitle = "Import Instruments Specification";
    ViewBag.Method = "Add Instruments Specification";
    ViewBag.DetailName = "Instruments Specification";
    ViewBag.DetailURL = "/ImportInstruments/Index";
}
<style>
    .select2-container {
        display: block;
    }

    h3 {
        color: #dc3545 !important;
        font-weight: bold;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3>Import Instruments Specification</h3>
            </div>
            @using (Html.BeginForm("UploadMasterInstrumentsExcel", "ImportInstruments", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmExcelForm" }))//onsubmit = "return myFunction()"
            {
                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <input type="hidden" id="rulesDetailsData" />
                                @Html.HiddenFor(model => model.Id,"Id")
                                @Html.LabelFor(model => model.Comment, "Rule Name")
                                @Html.TextBoxFor(p => p.Comment, new { @class = "form-control", @placeholder = "Rule Name" ,@name="Name"})
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Priority, "Priority")
                                @Html.TextBoxFor(p => p.Priority, new { @class = "form-control", @placeholder = "Priority" ,@name="Priority", type="number"})
                            </div>
                        </div>
                        <div class="col-6" id="divUploadFile">

                            <div class="custom-file form-group float-sm-left mr-3" style="width:230px">
                                <input type="file" id="FileUpload" name="FileUpload" class="custom-file-input">
                                <label id="lblRule" class="custom-file-label" style="text-align:left" for="file">Choose File</label>
                            </div>
                            <button type="submit" class="btn btn-info form-group float-sm-left mr-3 ">Import MasterInstruments</button>

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(() => {
            $('#FileUpload').on('change', function(e) {
                //get the file name
                var fileName = e.target.files[0].name;
                $(this).next('.custom-file-label').html(fileName);
            })
            $(document).on("submit", "#frmExcelForm", function(e) {
                e.preventDefault();
                $('#Loader').show();
                var form = $(this);
                form.ajaxSubmit({
                    beforeSubmit: function() {
                        if (!form.valid()) {
                            return false;
                            $('#Loader').hide();
                        }
                        else {
                            return true;
                            $('#Loader').show();
                        }
                    },
                    success: function(res) {
                        debugger
                        if (res.statusCode == 200) {
                            $('#FileUpload').val('');
                            $('#lblRule').html('Choose File')
                            NotifyMsg('success', res.message);
                            //$('#Id').val(res.response.id);
                            //$('#divUploadFile').hide();
                            $('#Loader').hide();
                            window.location.href = "/ImportInstruments/EditSpecificationRule?id=" + res.ruleId;
                        } else {
                            NotifyMsg('error', res.message);
                            $('#Loader').hide();
                        }
                    },
                    Errors: function() {
                        console.log('error', res.message);
                        NotifyMsg('error', res.message);
                        $('#Loader').hide();
                    }
                });
                return false;
            });
        });
    </script>
}