src/EPIDIWeb/Controllers/TermsConditionController.cs
using ClosedXML.Excel;
using DataTables.AspNet.AspNetCore;
using Epidi.Models.Paging;
using Epidi.Models.ViewModel.Common;
using Epidi.Models.ViewModel.Question;
using Epidi.Models.ViewModel.TermsCondition;
using Epidi.Service.ApplicationUserService;
using Epidi.Service.CountryService;
using Epidi.Service.TermsConditionService;
using Epidi.Service.UsersService;
using EPIDIWeb.Extensions;
using iTextSharp.text;
using iTextSharp.text.pdf;
using MathNet.Numerics.Distributions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage;
using NPOI.OpenXmlFormats.Dml.Diagram;
using System.Linq;
using NPOI.HPSF;
using Epidi.Models.Extensions;

namespace EPIDIWeb.Controllers
{
    public class TermsConditionController : Controller
    {
        private readonly ITermsConditionService _termsConditionService;
        private readonly ICountryService _countryService;
        private readonly IApplicationUserService _applicationUserService;
        private IConfiguration _Configuration;

        public TermsConditionController(ITermsConditionService termsConditionService,
            ICountryService countryService,
            IApplicationUserService applicationUserService,
            IConfiguration Configuration)
        {
            _termsConditionService = termsConditionService;
            _countryService = countryService;
            _applicationUserService = applicationUserService;
            _Configuration = Configuration;

        }

        public IActionResult Index()
        {
            ViewBag.Title = "Terms And Condition  List";
            return View();
        }
        [HttpPost]
        //public JsonResult GetTermsCondition()
        //{
        //	{
        //		long totalRecord = 0;
        //		long filteredRecord = 0;				
        //		//PageParam pageParam = new PageParam();
        //		//pageParam.Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
        //		//pageParam.Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
        //		//string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
        //		var response = _termsConditionService.Get();

        //		return Json(new { data = response });
        //	}
        //}

        [HttpPost]
        public async Task<JsonResult> TermsCondition_All()
        {
            {
                long totalRecord = 0;
                long filteredRecord = 0;
                var Draw = Request.Form["draw"].FirstOrDefault();
                PageParam pageParam = new PageParam();

                pageParam.Offset = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");

                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();

                pageParam.Limit = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
                string search = Convert.ToString(Request.Form["search[value]"].FirstOrDefault() ?? "");
                var response = await _termsConditionService.Get(pageParam, search);
                totalRecord = response.Item2;
                filteredRecord = response.Item2;

                var responseData = OrderByExtension.OrderBy(response.Item1.AsQueryable(), sortColumn, sortColumnDirection).ToList();

                return Json(new { draw = Draw, recordsTotal = totalRecord, recordsFiltered = filteredRecord, data = responseData });
            }
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> SaveTermsCondition(TermsConditionViewModel model)
        {
            try
            {
                ResponseViewModel responseViewModel = new ResponseViewModel();
                if (model != null)
                {
                    var res = await _termsConditionService.Upsert(model);
                    ////Delete Upload file for edit mode
                    var rem = await _termsConditionService.RemovePdfFile(res.Id, "");
                    for (int i = 0; i < model.FileList.Count; i++)
                    {
                        model.FileList[i].TermsConditionId = res.Id;
                        model.FileList[i].CountryId = model.CountryId;
                        model.FileList[i].Title = model.Title;

                        var resp = await _termsConditionService.TermsConditionFile_Upsert(model.FileList[i]);

                    }
                    if (res != null)
                    {
                        responseViewModel.Code = 200;
                        responseViewModel.Message = "TermsCondition Saved Successfully";
                    }
                    else
                    {
                        responseViewModel.Code = 400;
                        responseViewModel.Message = "TermsCondition Not Saved";
                    }
                    return Json(responseViewModel);
                }
                else
                {
                    return Json("");
                }
            }
            catch (Exception ex)
            {
                return Json(ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(long Id)
        {
            var termConditions = await _termsConditionService.GetTermsConditionById(Id);
            termConditions.FileList = await _termsConditionService.GetTermsConditionFilesById(Id);
            GetCountry();
            if (termConditions != null)
            {
                return View("AddTermsCondition", termConditions);
            }
            else
            {
                return View(new TermsConditionViewModel());
            }
        }

        [HttpGet]
        public IActionResult DeleteTermsCondition(int Id)
        {
            var res = _termsConditionService.DeleteTermsCondition(Id);
            return Json(res);
        }

        public IActionResult AddTermsCondition()
        {
            GetCountry();
            var model = new TermsConditionViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadPdf(List<IFormFile> FileUpload)
        {
            List<TCMultipleFilViewModel> FileList = new List<TCMultipleFilViewModel>();
            if (FileUpload != null)
            {
                var accountName = this._Configuration.GetSection("DocumentUploadCred")["BlobAccountName"];
                var accountKey = this._Configuration.GetSection("DocumentUploadCred")["BlobAccountKey"];
                var containerName = this._Configuration.GetSection("DocumentUploadCred")["Blobcontainername"];
                var fileUrl = this._Configuration.GetSection("DocumentUploadCred")["FileUrl"];
                var cloudStorageAccount = new CloudStorageAccount(new StorageCredentials(accountName, accountKey), true);
                var cloudBlobClient = cloudStorageAccount.CreateCloudBlobClient();
                var cloudBlobContainer = cloudBlobClient.GetContainerReference(containerName);


                for (int i = 0; i < FileUpload.Count; i++)
                {
                    TCMultipleFilViewModel tCMultipleFilViewModel = new TCMultipleFilViewModel();

                    var cloudBlockBlob = cloudBlobContainer.GetBlockBlobReference(FileUpload[i].FileName.ToString());

                    await using var memoryStream = new MemoryStream();
                    await FileUpload[i].CopyToAsync(memoryStream);
                    var streamBytes = memoryStream.ToArray();

                    using (Stream stream = new MemoryStream(streamBytes))
                    {
                        await cloudBlockBlob.UploadFromStreamAsync(stream);
                    }

                    tCMultipleFilViewModel.FileName = FileUpload[i].FileName.ToString();
                    tCMultipleFilViewModel.FileUrl = fileUrl + FileUpload[i].FileName.ToString();
                    FileList.Add(tCMultipleFilViewModel);
                }

                return PartialView("TCMultipleFile", FileList);
                //return Json(new { Data = fileName, StatusCode = 200, Message = "File Uploded successfully" });
            }
            else
            {
                return PartialView("TCMultipleFile", FileList);
            }
        }

        [HttpGet]
        public async Task<IActionResult> DownloadFile(string filePath, int UserId)
        {

            var user = await _applicationUserService.GetUserProfile(UserId);
            PdfReader pdfReader = new PdfReader(filePath);
            string fileName = $"termsandcondition-{UserId.ToString()}-{DateTime.UtcNow.ToUnixEpochDate().ToString()}.pdf";

            MemoryStream ms = new();
            PdfStamper pdfStamper = new PdfStamper(pdfReader, ms);
            AcroFields pdfFormFields = pdfStamper.AcroFields;
            pdfFormFields.RemoveXfa();

            var termscondition = await _termsConditionService.GetTermsCondition_ByCountryId(user.CountryId);

            if (termscondition.Exists(x => x.FileUrl.ToLower().Equals(filePath.ToLower()) && x.AutoFill))
            {
                if (pdfFormFields.GetFieldItem("topmostSubform[0].Page1[0].f_1[0]") != null)
                {
                    pdfFormFields.SetField("topmostSubform[0].Page1[0].f_1[0]", user.Name + " " + user.Surname);
                    pdfFormFields.SetFieldProperty("topmostSubform[0].Page1[0].f_1[0]", "textcolor", BaseColor.BLACK, null);
                    pdfFormFields.SetFieldProperty("topmostSubform[0].Page1[0].f_1[0]", "textsize", 12f, null);
                    pdfFormFields.RegenerateField("topmostSubform[0].Page1[0].f_1[0]");
                }

src/EPIDIWeb/Views/TermsCondition/AddTermsCondition.cshtml
@model Epidi.Models.ViewModel.TermsCondition.TermsConditionViewModel
@{
    Layout = null;

}
<style>
    .select2-container {
        display: block;
    }
</style>
@using (Html.BeginForm("SaveTermsCondition", "TermsCondition", FormMethod.Post, new { id = "termsconditionForm" }))
{
    @Html.HiddenFor(model=>model.Id,"Id")
    @Html.HiddenFor(model=>model.FileUrl,"FileUrl")
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                @Html.LabelFor(model => model.CountryName, "CountryName")
                @Html.DropDownListFor(model => model.CountryId, new SelectList(ViewBag.CountryList, "Value", "Text", Model.CountryId), "-- Select Country --", new { @class = "form-control js-select2" ,@name="CountryName" })
                <span asp-validation-for="CountryId"></span>
            </div>
        </div>
        <div class="col-3">
            <div class="form-group">
                @Html.LabelFor(model => model.Title, "Title")
                @Html.TextBoxFor(p => p.Title, new { @class = "form-control", @placeholder="Enter Here...", @name="Title" })
                <span asp-validation-for="Title"></span>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                @Html.TextAreaFor(p => p.TermsConditionText, new { @class = "form-control", @placeholder="Enter Here...", @name="TermsConditionText" })
                <span asp-validation-for="TermsConditionText"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="custom-file form-group float-sm-left mr-3" style="width:230px">
                <input type="file" id="FileUpload" name="FileUpload" class="custom-file-input" multiple>
                <label id="GatelblName" class="custom-file-label" style="text-align:left" for="file">Choose PDF</label>
            </div>
            <button type="button" onclick="UploadFile()" class="btn btn-info form-group float-sm-left mr-3 ">Import PDF</button>
        </div>
        <div class="col-12">
            @*@for (int i = 0; i < Model.FileList.Count; i++)
        {
        <span>@Model.FileList[i].FileName</span>
        }*@
            <table class="table" id="tbl_answer" style="border-collapse:collapse;width:100%;margin-top:20px;">

                @Html.Partial("TCMultipleFile", Model.FileList)
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-1">
            <div class="form-group">
                <label for="AutoFill">AutoFill</label>
            </div>
        </div>
        <div class="col-2">
            @Html.CheckBoxFor(model => model.AutoFill)
            <span asp-validation-for="Title"></span>
            <div class="form-group">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
        </div>
    </div>

    @*<div id="add">
        <div class="row">


        </div>
    </div>
    <div id="edit">
    </div>*@
    <div class="modal-footer">



        <button value="AddTermsCondition" name="action" type="submit" class="btn btn-primary">Save</button>
    </div>
}
<script>
    var isFileUpload = true;
    $(document).ready(() => {
        $('#FileUpload').on('change', function (e) {
            isFileUpload = false;
            var fileName = e.target.files[0].name;
            $(this).next('.custom-file-label').html(fileName);
        })

        $("body").on("click", ".deletefile", function () {
            debugger;
            var tblid = $(this).closest("tr").attr('id');
            var fileUrl = $(this).closest("tr").find("#hdnFileName").val();
            var id = $('#Id').val();
            $.ajax({
                type: "POST",
                url: '/TermsCondition/RemoveFile',
                data: { FileUrl: fileUrl, Id: id },
                success: function (res) {

                    if (res.statusCode == 200) {

                        $("#" + tblid).remove();
                        NotifyMsg('success', res.message);


                    } else {
                        NotifyMsg('error', res.message);
                    }
                },
                error: function (errorTemp) {
                    NotifyMsg('error', errorTemp);
                    console.log('error', errorTemp);
                }
            })
        });

    });

    function UploadFile() {
        
        var fdata = new FormData();

        //var fileInput = $('#FileUpload');
        var fileInput = document.getElementById('FileUpload');

        for (i = 0; i < fileInput.files.length; i++) {

            var sfilename = fileInput.files[i].name;
            let srandomid = Math.random().toString(36).substring(7);

            fdata.append("FileUpload", fileInput.files[i]);
            isFileUpload = true;
        }

        $.ajax({
            type: "POST",
            url: '/TermsCondition/UploadPdf',
            data: fdata,
            processData: false,
            contentType: false,
            dataType: "html",
            success: function (res) {

                if (res != null) {
                    debugger;
                    if ($('#tbl_answer tr').length >= 1) {
                        $("#tbl_answer").append(res);
                        $('#FileUpload').val('');

                        $('#GatelblName').html('Choose File')
                        //var fileName = $('#hdnFileName').val('');
                        //$('#FileUrl').val(fileName);

                    }
                    else {
                        $("#tbl_answer").html(res);
                        $('#FileUpload').val('');
                        $('#GatelblName').html('Choose File')
                        //var fileName = $('#hdnFileName').val();
                        //$('#FileUrl').val(fileName);
                    }

                    //NotifyMsg('success', res.message);

                } else {
                    NotifyMsg('error', res.message);
                }
            },
            error: function (errorTemp) {

                NotifyMsg('error', errorTemp);
                console.log('error', errorTemp);
            }
        })
    }


</script>

src/EPIDIWeb/Views/TermsCondition/Index.cshtml
@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    ViewBag.PageTitle = "Terms and Condition";
    ViewBag.Method = "Terms and Condition";
}
<style>
    .select2-container {
        display: inline-block;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="col-12">
                    <button id="btnAddTCs" type="button" class="btn btn-outline-primary btn-uppercase float-right">
                        <i class="ti-plus mr-2"></i> Add T & Cs
                    </button>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="tblTCList" class="table table-bordered table-striped">
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<div class="modal fade" id="frmModelTermsCondition">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-title">
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
    <script src="~/js/summernote/summernote.js"></script>
    <script src="~/js/summernote/summernote.min.js"></script>

    <script>
        $(document).ready(() => {
            GetTermsConditionListData("");          
            $("body").on("click", "#btnAddTCs", function () {
                //$("#frmModelTermsCondition").modal("show");
                AddModal("/TermsCondition/AddTermsCondition", "Add New Terms & Condition");
                let summernoteOptions = {
                    height: 100
                }                
                $('#TermsConditionText').summernote(summernoteOptions);
            });
            $(document).on('click', '#change', function () {
                summernoteOptions.height = 100;
                let content = $('#TermsConditionText').summernote('code');
                $('#TermsConditionText').summernote('destroy');
                $('#TermsConditionText').summernote(summernoteOptions);
                $('#TermsConditionText').summernote('code', content);
            });
            $("body").on("submit", "#termsconditionForm", function (e) {
                if (!isFileUpload) {
                    Toast.fire({
                        icon: 'error',
                        title: "please import the file."
                    });
                    return false;
                }
                e.preventDefault();
                Validation();
                var form = $(this);
                form.ajaxSubmit({
                    beforeSubmit: function () {
                        if (!form.valid ()) {
                           return false;
                         }
                         else {
                            return true;
                        }
                    },
                    success: function (res) {
                        if (res.code == 200) {
                            $("#frmModel").modal('hide');
                            $("#termsconditionForm").resetForm();
                            GetTermsConditionListData("");
                            Toast.fire({
                                icon: 'success',
                                title: " " + res.message
                            })
                        } else {
                            //$("#Loader").hide();
                            Toast.fire({
                                icon: 'error',
                                title: " " + res.message
                            })
                        }
                    },
                    Errors: function () {
                        //$("#Loader").hide();
                        Toast.fire({
                            icon: 'error',
                            title: " " + res[0].message
                        })
                    }
                });
                return false;
            });
        });


        function Validation() {
            $('#termsconditionForm').validate({
                rules: {
                    CountryName: {
                        required: true
                    },
                    CountryId: {
                        required: true
                    },
                    TermsConditionText:
                    {
                        required: true
                    },
                    Title:
                    {
                        required: true
                    }
                },
                messages: {
                    CountryName: {
                        required: "Please enter Countryname"
                    },
                    CountryId: {
                        required: "Please enter Countryname"
                    },
                    TermsConditionText: {
                        required: "Please enter TermsConditionText"
                    },
                    Title: {
                        required: "Please enter Title"
                    },
                },
                errorElement: 'span',
                errorPlacement: function (error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function (element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function (element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                }
            });
        }

        function GetTermsConditionListData(Name) {
            $('#tblTCList').DataTable(
                {
                    ajax: {
                        url: "/TermsCondition/TermsCondition_All",
                        type: "post",
                        data: { Name: Name }
                    },
                    "language": {
                        "aria": {
                            "sortAscending": ": activate to sort column ascending",
                            "sortDescending": ": activate to sort column descending"
                        },
                        "emptyTable": "No data available in table",
                        "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                        "infoEmpty": "No entries found",
                        "infoFiltered": "(filtered1 from MAX total entries)",
                        //"lengthMenu": "MENU entries",
                        "search": "Search:",
                        "zeroRecords": "No matching records found"
                    },
                    destroy: true,
                    autoWidth: false,
                    paging: true,
                    pageLength: 10,
                    processing: true,
                    serverSide: true,
                    filter: true,
                    columnDefs: [{
                        //"targets": [0],
                        "visible": false,
                        "searchable": false
                    }],
                    columns: [                       
                        {
                            "title": "Id", "data": "id", "name": "Id", "orderable": true, "width": "3%"
                        },
                        {
                            "title": "Title", "data": "title", "name": "title", "orderable": true, "width": "3%"
                        },
                        {
                            "title": "Terms & Condition", "data": "TermsConditionText", "name": "TermsConditionText",
                            "render": function (data, type, row) {
                               
                                var str = removeTags(row.termsConditionText);

                                return str.length > 70 ? '<span data-toggle="tooltip" title= \"' + str + '\">' + str.substr(0, 70) + '...</span>' : str;
                            },
                            "orderable": true, "width": "3%"
                        },
                        {
                            "title": "CountryName", "data": "countryName", "name": "countryName", "orderable": true, "width": "3%"
                        },
                        {
                            "title": "AutoFill", "data": "autoFill", "name": "autoFill",  "orderable": true, "width": "3%"
                        },
                        {
                            "title": "Action", "data": "Id",
                            "render": function (data, type, row) {
                                var html = "<div class='btn-group dropleft'>";
                                html += "<a class='btn btn-success mr-1' href='javascript:void(0);' onclick='edit(this);' data-uri='/TermsCondition/Edit?Id=" + row.id + "' ><i class='fa fa-edit'></i></a>";
                                html += "<a class='btn btn-danger edt-dlt mr-1' href='javascript:void(0);' data-uri='/TermsCondition/DeleteTermsCondition?Id=" + row.id + "' ><i class='fa fa-trash'></i></a>";
                                html += "</div>";
                                return html;
                            }
                            , "orderable": false, "width": "3%"
                        },
                    ]
                }
            );
        }
        function removeTags(str) {
            if ((str === null) || (str === ''))
                return false;
            else
                str = str.toString();

            // Regular expression to identify HTML tags in
            // the input string. Replacing the identified
            // HTML tag with a null string.
            return str.replace(/(<([^>]+)>)/ig, '');
        }
        function AddTermsConditionModal(url, title) {
            
            $.ajax({
                url: url,
                Type: 'get',
                dataType: 'html',
                success: function (result) {
                    if (result != "undefined") {
                        $("#frmModelTermsCondition .modal-body").html(result);
                        $("#frmModelTermsCondition .modal-title").text(title);
                      }
                },
                error: function (result) {
                    alert("Error");
                }
            });
        }

        function edit(obj) {
            debugger
                 var uri = $(obj).attr('data-uri');
            var header = $(obj).closest('table').attr('edit-header');
            $.get(uri, { async: false }, function (data) {
                $("#frmModel .modal-body").html(data);
                $("#frmModel .modal-title").html(header);
               
                $("#frmModel").modal('show');
                
                let summernoteOptions = {
                    height: 100
                }
                $('#TermsConditionText').summernote(summernoteOptions);
                 }).fail(function () {
                //NotifyMsg("getting errors", "warning");

            });          
        }
    </script>
}

src/EPIDIWeb/Views/TermsCondition/TCMultipleFile.cshtml
@model List<Epidi.Models.ViewModel.TermsCondition.TCMultipleFilViewModel>
@{
	Layout = null;
}
@foreach (var item in Model)
{
	@Html.Partial("TCSingleFile", item)
}

src/EPIDIWeb/Views/TermsCondition/TCSingleFile.cshtml
@using HtmlHelpers.BeginCollectionItemCore;

@model Epidi.Models.ViewModel.TermsCondition.TCMultipleFilViewModel
@{
	Layout = null;
	Guid guid = Guid.NewGuid();
}
	<tr class="tr-row" id="@guid">
	@using (Html.BeginCollectionItem("FileList"))
	{
		<td style="padding-bottom: 0px;vertical-align: top;border-top: 0px solid #dee2e6;">
			<div class="form-group">
				@Html.HiddenFor(p => p.Id,new { id = "hdnId" })
				@Html.HiddenFor(p => p.FileName,new { id = "hdnFileName" })
				@Html.HiddenFor(p => p.FileUrl,new { id = "hdnFileUrl" })
				@Html.LabelFor(p => p.FileName, Model.FileName)
			</div>
		</td>
		<td style="padding-bottom: 0px;vertical-align: top;border-top: 0px solid #dee2e6;">
			<a href="@Model.FileUrl" class="btn btn-info form-group float-sm-left mr-3" target="_blank" style="background-color: #17a2b8">Download File</a>
		</td>
		<td style="padding-bottom: 0px;vertical-align: top;border-top: 0px solid #dee2e6;">
			<a class='btn btn-danger mr-1 deletefile' href='javascript:void(0);' style='background-color: #dc3545'><i class='fa fa-trash'></i></a>
		</td>
	}
</tr>